name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**/README.md'

jobs:


    buildDebug:
        name: Debug build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Run debug build
                run: ./gradlew assembleDebug
                    
            -   name: setup output
                run: |
                     echo "TIME_NOW=$(date "+%Y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
            
            -   name: Upload binaries to release
                uses: svenstaro/upload-release-action@v2
                with:
                    repo_token: ${{ secrets.FDROID_CLASSIC_RELEASE }}
                    file: ./app/build/outputs/apk/debug/app-debug.apk
                    #tag: ${{ env.TIME_NOW }}
                    tag: ${{ github.ref }}
                    body: "This is my release text"
