name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**/README.md'

jobs:


    buildDebug:
        name: Debug build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Run debug build
                run: ./gradlew assembleDebug
                    
            -   name: setup output
                run: |
                     echo "TIME_NOW=$(date "+%Y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV

            -   name: Upload artifact to GitHub
                uses: actions/upload-artifact@v2
                with:
                    name: storage-usb-debug.apk
                    path: ./app/build/outputs/apk/debug/app-debug.apk

